package lslab.algorithm.question.math;

import java.util.ArrayList;

/*
 * http://contestcoding.wordpress.com/2013/04/12/triangular-numbers/
 * TRIANGULAR NUMBERS
 * Triangular numbers are the sequence of numbers generated by forming objects inside a triangle.
 *	1, 3, 6, 10, 15, 21…
 *	Find the sum of all 3-digit triangular numbers.
 *  Remember, to solve this problem and appear on the leaderboard, 
 *  email both your solution and your source code (in any language) to lewiscornwall13@gmail.com. Good luck!!
 */

public class TriangularNumber {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		ArrayList<Integer> al = new ArrayList<Integer>();
		int n = 1;
		int tn = 0;
		while (tn < 1000) {
			tn = n * (n + 1) / 2;
			if (tn >= 100 && tn < 1000) {
				System.out.println(tn);
				al.add(tn);
			}
			n++;

		}
		int sum = 0;
		for (int i = 0; i < al.size(); i++) {
			sum = sum + al.get(i);
		}
		System.out.println(sum);
	}

}
